using System;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using BlingBag;
using Castle.DynamicProxy;
using Starscream.Domain;
using Starscream.Notifications;

namespace Starscream.Web.Api.Infrastructure.Configuration
{
    public class BlingConfiguratorLogger : IBlingConfigurator<DomainEvent>
    {
        readonly IBlingConfigurator<DomainEvent> _decorated;

        public BlingConfiguratorLogger(IBlingConfigurator<DomainEvent> decorated )
        {
            _decorated = decorated;
        }

        public object GetHandler(object obj)
        {
            return _decorated.GetHandler(obj);
        }



        public Func<EventInfo, bool> EventSelector
        {
            get { return x => _decorated.EventSelector(x); } 
        }

        public DomainEvent HandleEvent {
            get
            {
                return x => _decorated.HandleEvent(x);
            }
        }
    }

    public class BlingConfigurator : IBlingConfigurator<DomainEvent>
    {
        readonly IBlingDispatcher _dispatcher;

        public BlingConfigurator(IBlingDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        #region IBlingConfigurator<DomainEvent> Members

        public object GetHandler(object obj)
        {
            
            return obj;
        }

        public Func<EventInfo, bool> EventSelector
        {
            get { return x => x.EventHandlerType == typeof(DomainEvent); }
        }

        public DomainEvent HandleEvent
        {
            get { return x =>
                         {
                             try
                             {
                                 _dispatcher.Dispatch(x);
                             }
                             catch (Exception ex)
                             {
                                 //in an event queue, any exception would not affect this web server,
                                 //so, to simulate an event queue and prevent us from depending on
                                 //exception behavior generated by event handlers, this "catch" 
                                 //intentionally does nothing. -Byron
                             }
                         }; }
        }

        #endregion
    }
}